AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instances for the compute tier

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String
  EC2SecurityGroup:
    Type: String
  TargetGroupArn:
    Type: String

Resources:
  Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.nano
      KeyName: !Ref KeyName
      ImageId: ami-0c2b8ca1dad447f8a
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install nginx1 -y
          systemctl enable nginx
          systemctl start nginx
      Tags:
        - Key: Name
          Value: Ec21

  Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.nano
      KeyName: !Ref KeyName
      ImageId: ami-0c2b8ca1dad447f8a
      SubnetId: !Ref PublicSubnet2
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install nginx1 -y
          systemctl enable nginx
          systemctl start nginx
      Tags:
        - Key: Name
          Value: Ec22

  # Association des instances au Target Group via un TargetGroupAttachment (nécessaire pour ALB)
  TargetGroupAttachment1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroupAttachment
    Properties:
      TargetGroupArn: !Ref TargetGroupArn
      TargetId: !Ref Instance1
      Port: 80

  TargetGroupAttachment2:
    Type: AWS::ElasticLoadBalancingV2::TargetGroupAttachment
    Properties:
      TargetGroupArn: !Ref TargetGroupArn
      TargetId: !Ref Instance2
      Port: 80
