AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL database with subnet group

Parameters:
  VPCId:
    Type: String
  DatabaseSubnet1:
    Type: String
  DatabaseSubnet2:
    Type: String
  RDSSecurityGroup:
    Type: String

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "DB subnet group for RDS instance"
      SubnetIds:
        - !Ref DatabaseSubnet1
        - !Ref DatabaseSubnet2
      Tags:
        - Key: Name
          Value: my-db-subnet-group

  RDSInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      DBInstanceIdentifier: my-rds
      Engine: mysql
      EngineVersion: '5.7'
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      StorageType: gp2
      MasterUsername: admin
      MasterUserPassword: password
      MultiAZ: true
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 1
      SkipFinalSnapshot: true
      Tags:
        - Key: Name
          Value: my-rds-instance

Outputs:
  RDSInstanceEndpoint:
    Description: Endpoint address of the RDS instance
    Value: !GetAtt RDSInstance.Endpoint.Address

  RDSInstanceId:
    Description: ID of the RDS instance
    Value: !Ref RDSInstance
