AWSTemplateFormatVersion: '2010-09-09'
Description: Master stack to orchestrate nested stacks for 3-tier infra

Parameters:
  KeyName:
    Description: SSH Key Pair for EC2
    Type: AWS::EC2::KeyPair::KeyName

Resources:

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://terraform-backend-stevy01.s3.amazonaws.com/templates/network.yaml

  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack  
    Properties:
      TemplateURL: https://terraform-backend-stevy01.s3.amazonaws.com/templates/securitygroups.yaml
      Parameters:
        VPCId: !GetAtt NetworkStack.Outputs.VPCId

  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://terraform-backend-stevy01.s3.amazonaws.com/templates/alb.yaml
      Parameters:
        PublicSubnet1: !GetAtt NetworkStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt NetworkStack.Outputs.PublicSubnet2
        ALBSecurityGroup: !GetAtt SecurityGroupsStack.Outputs.ALBSecurityGroup
        VPCId: !GetAtt NetworkStack.Outputs.VPCId

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://terraform-backend-stevy01.s3.amazonaws.com/templates/compute.yaml
      Parameters:
        KeyName: !Ref KeyName
        PublicSubnet1: !GetAtt NetworkStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt NetworkStack.Outputs.PublicSubnet2
        EC2SecurityGroup: !GetAtt SecurityGroupsStack.Outputs.EC2SecurityGroup
        TargetGroupArn: !GetAtt ALBStack.Outputs.TargetGroupArn

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://terraform-backend-stevy01.s3.amazonaws.com/templates/database.yaml
      Parameters:
        VPCId: !GetAtt NetworkStack.Outputs.VPCId
        DatabaseSubnet1: !GetAtt NetworkStack.Outputs.DatabaseSubnet1
        DatabaseSubnet2: !GetAtt NetworkStack.Outputs.DatabaseSubnet2
        RDSSecurityGroup: !GetAtt SecurityGroupsStack.Outputs.RDSSecurityGroup

Outputs:
  LoadBalancerDNS:
    Description: DNS name of the Load Balancer
    Value: !GetAtt ALBStack.Outputs.LoadBalancerDNS
