AWSTemplateFormatVersion: '2010-09-09'
Description: Master Stack

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/terraform-backend-stevy01/templates/network.yaml

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/terraform-backend-stevy01/templates/compute.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnet1Id: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt VPCStack.Outputs.PublicSubnet2Id
        KeyName: !Ref KeyName

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/terraform-backend-stevy01/templates/database.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
