name: Deploy Dev Stack

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1 

      - name: Deploy CloudFormation Stack in Dev
        run: |
          aws cloudformation deploy \
            --template-file templates/master-template.yaml \
            --stack-name three-tier-dev \
            --parameter-overrides file://parameters/dev-parameters.json \
            --capabilities CAPABILITY_NAMED_IAM
